### PR TITLE
[NO SQUASH] Maintenance work

### PR DESCRIPTION
**Pull request by SmallJoker**
See commit descriptions for reference.

The deprecation warnings can be seen with the setting `deprecated_lua_api_handling = log`.

### CODE REVIEW

**Comment by SmallJoker** [comment]
Will merge in a few days unless there are objections.

**Comment by rautyrauty** [comment]
I also suggest moving changelog to a separate file and updating the version to 1.8.0.

**Comment by SmallJoker** [comment]
@rautyrauty Good idea. The changelog is often not very interesting. I'm however not wiling to track versions of this repository. It's easier to move it to rolling release, like now done in Minetest Game and other minetest-mods repositories that are kept alive by new contributors.

**Comment by rautyrauty** [comment]
It would be good to send the sources to the src folder, with the exception of init.lua and similar files needed for mod initialization.

**Pull request merged**
